-- SQL Schema for Planify Supabase Migration

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    bio TEXT,
    website TEXT,
    avatar TEXT,
    notification_preference TEXT DEFAULT '1d',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    date TEXT,
    time TEXT,
    end_time TEXT,
    category TEXT,
    location TEXT,
    type TEXT DEFAULT 'task',
    priority TEXT,
    done INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Schedules Table
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    schedule_date TEXT,
    start_time TEXT,
    end_time TEXT,
    location TEXT,
    status TEXT DEFAULT 'upcoming',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    role TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert Dummy Data for initial testing
INSERT INTO users (name, username, email, password, bio, website)
VALUES ('Alex Johnson', 'alex_j', 'alex.j@example.com', 'password123', 'Product Designer & Coffee Enthusiast. Passionate about building modern web experiences.', 'alexj.dev')
ON CONFLICT DO NOTHING;

INSERT INTO testimonials (user_id, content, rating, role) 
VALUES (1, 'Planora membantu saya mengatur jadwal meeting yang sangat padat tanpa merasa kewalahan. Desainnya benar-benar juara!', 5, 'Creative Director');

